category_dict_icml15 = {
    "Bandit Learning" : [["Bandits"]],
    "Bayesian Nonparametrics" : [["Baysian Nonparametrics"]],
    "Bayesian Optimization" : [["Optimization"], ["Baysian Optimization"]],
    "Causality" : [["Causality"]],
    "Clustering" : [["Clustering"]],
    "Computational Advertising And Social Science" : [["Computational Advertising", "Social Science"]],
    "Deep Learning" : [["Deep Learning"]],
    "Deep Learning And Vision" : [["Deep Learning", "Computer Vision"]],
    "Deep Learning Computations" : [["Deep Learning"]],
    "Distributed Optimization" : [["Optimization"], ["Distributed Optimization"]],
    "Feature Selection" : [["Feature Selection"]],
    "Gaussian Processes" : [["Gaussian Processes"]],
    "Hashing" : [["Hashing"]],
    "Kernel Methods" : [["Kernel Methods"]],
    "Large Scale Learning" : [["Large Scale Learning"]],
    "Learning Theory" : [["Learning Theory"]],
    "Manifold Learning" : [["Manifold Learning"]],
    "Matrix Factorization" : [["Matrix Factorization"]],
    "Monte Carlo Methods" : [["Monte Carlo Methods"]],
    "Natural Language Processing" : [["Natural Language Processing"]],
    "Networks And Graphs" : [["Networks", "Graph Analysis"]],
    "Online Learning" : [["Online Learning"]],
    "Optimization" : [["Optimization"]],
    "Privacy" : [["Privacy"]],
    "Probabilistic Models" : [["Probabilistic Models"]],
    "Ranking Learning" : [["Ranking Learning"]],
    "Reinforcement Learning" : [["Reinforcement Learning"]],
    "Sparse Optimization" : [["Optimization"], ["Sparse Optimization"]],
    "Sparsity" : [["Sparsity"]],
    "Structured Prediction" : [["Structured Prediction"]],
    "Submodularity" : [["Submodularity"]],
    "Supervised Learning" : [["Supervised Learning"]],
    "Time Series Analysis" : [["Time-Series"]],
    "Topic Models" : [["Probabilistic Models"]],
    "Transfer Learning" : [["Transfer Learning"]],
    "Unsupervised Learning" : [["Unsupervised Learning"]],
    "Variational Inference" : [["Approximate Inference"]],
    "Vision" : [["Computer Vision"]]
}

category_dict_icml16 = {
    "Applications and Time-Series Analysis" : [["Applications", "Time-Series"]],
    "Approximate Inference" : [["Approximate Inference"]],
    "Bandit Problems" : [["Bandits"]],
    "Bayesian Nonparametric Methods" : [["Baysian Nonparametrics"]],
    "Causal Inference" : [["Causal Inference"]],
    "Clustering" : [["Clustering"]],
    "Crowdsourcing and Interactive Learning" : [["Crowdsourcing", "Interactive Learning"]],
    "Dimensionality Reduction / Private Learning" : [["Dimensionality Reduction", "Privacy"]],
    "Feature Selection and Dimensionality Reduction" : [["Feature Selection", "Dimensionality Reduction"]],
    "Gaussian Processes" : [["Gaussian Processes"]],
    "Graph Analysis/ Spectral Methods" : [["Graph Analysis", "Spectral Methods"]],
    "Graphical Models" : [["Probabilistic Models"], ["Graphical Models"]],
    "Kernel Methods" : [["Kernel Methods"]],
    "Large Scale Learning and Big Data" : [["Large Scale Learning"]],
    "Learning Theory" : [["Learning Theory"]],
    "Machine Learning Applications" : [["Applications"]],
    "Matrix Factorization / Neuroscience Applications" : [["Matrix Factorization", "Neuroscience Applications"]],
    "Matrix Factorization and Related Topics" : [["Matrix Factorization"]],
    "Metric and  Manifold Learning / Kernel Methods" : [["Metric Learning", "Manifold Learning", "Kernel Methods"]],
    "Monte Carlo Methods" : [["Monte Carlo Methods"]],
    "Multi-label, multi-task, and neural networks" : [["Multi-Label Learning", "Multi-Task Learning"], ["Deep Learning"]],
    "Neural Networks and Deep Learning" : [["Deep Learning"]],
    "Neural Networks and Deep Learning&nbsp;I" : [["Deep Learning"]],
    "Neural Networks and Deep Learning&nbsp;II" : [["Deep Learning"]],
    "Neural Networks and Deep Learning&nbsp;II (Computer Vision)" : [["Deep Learning"], ["Computer Vision"]],
    "Online Learning" : [["Online Learning"]],
    "Optimization" : [["Optimization"]],
    "Optimization (Combinatorial)" : [["Optimization"], ["Combinatorial Optimization"]],
    "Optimization (Continuous)" : [["Optimization"], ["Continuous Optimization"]],
    "Optimization / Online Learning" : [["Optimization", "Online Learning"]],
    "Privacy, Anonymity, and Security" : [["Privacy"]],
    "Ranking and Preference Learning" : [["Ranking Learning", "Preference Learning"]],
    "Reinforcement Learning" : [["Reinforcement Learning"]],
    "Sampling / Kernel Methods" : [["Sampling", "Kernel Methods"]],
    "Sparsity and Compressed Sensing" : [["Sparsity", "Compressed Sensing"]],
    "Statistical Learning Theory" : [["Statistical Learning Theory"]],
    "Structured Prediction / Monte Carlo Methods" : [["Structured Prediction", "Monte Carlo Methods"]],
    "Supervised Learning" : [["Supervised Learning"]],
    "Transfer Learning / Learning Theory" : [["Transfer Learning", "Learning Theory"]],
    "Unsupervised Learning / Applications" : [["Unsupervised Learning", "Applications"]],
    "Unsupervised Learning / Representation Learning" : [["Unsupervised Learning", "Representation Learning"]]
}

category_dict_icml17 = {
    "Active Learning" : [["Active Learning"]],
    "Applications" : [["Applications"]],
    "Bayesian Nonparametrics" : [["Baysian Nonparametrics"]],
    "Bayesian Optimization" : [["Optimization"], ["Baysian Optimization"]],
    "Causal Inference" : [["Causal Inference"]],
    "Clustering" : [["Clustering"]],
    "Combinatorial Optimization" : [["Optimization"], ["Combinatorial Optimization"]],
    "Continuous Control" : [["Continuous Control"]],
    "Continuous Optimization" : [["Optimization"], ["Continuous Optimization"]],
    "Deep Generative Models" : [["Deep Learning"], ["Deep Generative Models"]],
    "Deep Learning" : [["Deep Learning"]],
    "Deep Learning : Analysis": [["Deep Learning"]],
    "Deep Learning : Backprop": [["Deep Learning"]],
    "Deep Learning : Fisher Approximations": [["Deep Learning"]],
    "Deep Learning : Hardware": [["Deep Learning"]],
    "Deep Learning : Invariances": [["Deep Learning"]],
    "Deep Learning : Learning To Learn": [["Deep Learning"]],
    "Deep Learning : Metalearning": [["Deep Learning"]],
    "Deep Learning : Probabilistic": [["Deep Learning"], ["Probabilistic Models"]],
    "Deep Learning Theory" : [["Deep Learning"], ["Deep Learning Theory"]],
    "Deep Reinforcement Learning" : [["Deep Reinforcement Learning"], ["Reinforcement Learning"]],
    "Distributed Optimization" : [["Optimization"], ["Distributed Optimization"]],
    "Ensemble Methods" : [["Ensemble Methods"]],
    "Game Theory And Multiagents" : [["Game Theory", "Multi-Agent Learning"]],
    "Gaussian Processes" : [["Gaussian Processes"]],
    "Healthcare" : [["Healthcare"]],
    "High Dimensional Estimation" : [["High Dimensional Estimation"]],
    "Infomation Theory" : [["Information Theory"]],
    "Kernel Methods" : [["Kernel Methods"]],
    "Language" : [["Natural Language Processing"]],
    "Large Scale Learning" : [["Large Scale Learning"]],
    "Latent Feature Models" : [["Latent Feature Models"]],
    "Learning Theory" : [["Learning Theory"]],
    "Matrix Factorization" : [["Matrix Factorization"]],
    "Metric Learning" : [["Metric Learning"]],
    "Ml And Programming" : [["Ml And Programming"]],
    "Monte Carlo Methods" : [["Monte Carlo Methods"]],
    "Networks And Relational Learning" : [["Networks", "Relational Learning"]],
    "Online Learning" : [["Online Learning"]],
    "Privacy And Security" : [["Privacy"]],
    "Probabilistic Inference" : [["Approximate Inference"]],
    "Probabilistic Learning" : [["Probabilistic Models"]],
    "Ranking And Preferences" : [["Ranking Learning", "Preference Learning"]],
    "Recurrent Neural Networks" : [["Recurrent Neural Networks"]],
    "Reinforcement Learning" : [["Reinforcement Learning"]],
    "Robust Estimation" : [["Robustness"]],
    "Semisupervised And Curriculum Learning" : [
            ["Semi-Supervised Learning", "Curriculum Learning"]
        ],
    "Sparsity" : [["Sparsity"]],
    "Spectral Methods" : [["Spectral Methods"]],
    "Structured Prediction" : [["Structured Prediction"]],
    "Supervised Learning" : [["Supervised Learning"]],
    "Time Series" : [["Time-Series"]],
    "Transfer And Multitask Learning": [["Transfer Learning", "Multi-Task Learning"]]
}

category_dict_icml18 = {
    "Active Learning" : [["Active Learning"]],
    "Approximate Inference" : [["Approximate Inference"]],
    "Causal Inference" : [["Causal Inference"]],
    "Clustering" : [["Clustering"]],
    "Computer Vision" : [["Computer Vision"]],
    "Deep Learning (Adversarial)" : [["Deep Learning", "Adversarial"]],
    "Deep Learning (Bayesian)" : [["Deep Learning", "Baysian Deep Learning"]],
    "Deep Learning (Neural Network Architectures)" : [["Deep Learning", "Architectures"]],
    "Deep Learning (Theory)" : [["Deep Learning", "Deep Learning Theory"]],
    "Dimensionality Reduction" : [["Dimensionality Reduction"]],
    "Feature Selection" : [["Feature Selection"]],
    "Gaussian Processes" : [["Gaussian Processes"]],
    "Generative Models" : [["Generative Models"]],
    "Graphical Models" : [["Probabilistic Models"], ["Graphical Models"]],
    "Kernel Methods" : [["Kernel Methods"]],
    "Large Scale Learning and Big Data" : [["Large Scale Learning"]],
    "Matrix Factorization" : [["Matrix Factorization"]],
    "Monte Carlo Methods" : [["Monte Carlo Methods"]],
    "Multi-Agent Learning" : [["Multi-Agent Learning"]],
    "Natural Language and Speech Processing" : [["Natural Language Processing", "Speech Processing"]],
    "Networks and Relational Learning" : [["Networks", "Relational Learning"]],
    "Online Learning" : [["Online Learning"]],
    "Optimization (Bayesian)" : [["Optimization"], ["Baysian Optimization"]],
    "Optimization (Combinatorial)" : [["Optimization"], ["Combinatorial Optimization"]],
    "Optimization (Convex)" : [["Optimization"], ["Convex Optimization"]],
    "Optimization (Non-convex)" : [["Optimization"], ["Non-Convex Optimization"]],
    "Other Applications" : [["Applications"]],
    "Other Models and Methods" : [["Other Models and Methods"]],
    "Parallel and Distributed Learning" : [["Optimization"], ["Distributed Optimization"]],
    "Privacy, Anonymity, and Security" : [["Privacy"]],
    "Ranking and Preference Learning" : [["Ranking Learning", "Preference Learning"]],
    "Reinforcement Learning" : [["Reinforcement Learning"]],
    "Representation Learning" : [["Representation Learning"]],
    "Society Impacts of Machine Learning" : [["Society Impacts of Machine Learning"]],
    "Sparsity and Compressed Sensing" : [["Sparsity", "Compressed Sensing"]],
    "Spectral Methods" : [["Spectral Methods"]],
    "Statistical Learning Theory" : [["Statistical Learning Theory"]],
    "Structured Prediction" : [["Structured Prediction"]],
    "Supervised Learning" : [["Supervised Learning"]],
    "Time-Series Analysis" : [["Time-Series"]],
    "Transfer and Multi-Task Learning" : [["Transfer Learning", "Multi-Task Learning"]],
    "Unsupervised Learning" : [["Unsupervised Learning"]]
}

category_dict_icml19 = {
    "Active Learning" : [["Active Learning"]],
    "Adversarial Examples" : [["Adversarial"]],
    "Applications" : [["Applications"]],
    "Applications: Computer Vision" : [["Applications"], ["Computer Vision"]],
    "Applications: Natural Language Processing" : [["Applications"], ["Natural Language Processing"]],
    "Approximate Inference" : [["Approximate Inference"]],
    "Bandits and Multiagent Learning" : [["Bandits", "Multi-Agent Learning"]],
    "Bayesian Deep Learning" : [["Deep Learning"], ["Baysian Deep Learning"]],
    "Bayesian Methods" : [["Baysian Methods"]],
    "Bayesian Non-parametrics" : [["Baysian Nonparametrics"]],
    "Causality" : [["Causality"]],
    "Combinatorial Optimization" : [["Combinatorial Optimization"]],
    "Convex Optimization" : [["Optimization"], ["Convex Optimization"]],
    "Deep Generative Models" : [["Deep Learning"], ["Deep Generative Models"]],
    "Deep Learning" : [["Deep Learning"]],
    "Deep Learning Algorithms" : [["Deep Learning"]],
    "Deep Learning Architectures" : [["Deep Learning"], ["Architectures"]],
    "Deep Learning Optimization" : [["Deep Learning"], ["Optimization"]],
    "Deep Learning Theory" : [["Deep Learning"], ["Deep Learning Theory"]],
    "Deep RL" : [["Deep Learning"], ["Deep Reinforcement Learning"]],
    "Deep Sequence Models" : [["Deep Learning"]],
    "Fairness" : [["Fairness"]],
    "Gaussian Processes" : [["Gaussian Processes"]],
    "General ML" : [["General ML"]],
    "Generative Adversarial Networks" : [["Generative Models"]],
    "Generative Models" : [["Generative Models"]],
    "Information Theory and Estimation" : [["Information Theory", "Estimation"]],
    "Interpretability" : [["Interpretability"]],
    "Kernel Methods" : [["Kernel Methods"]],
    "Large Scale Learning and Systems" : [["Large Scale Learning"]],
    "Learning Theory" : [["Learning Theory"]],
    "Learning Theory: Games" : [["Learning Theory", "Games"]],
    "Monte Carlo Methods" : [["Monte Carlo Methods"]],
    "Networks and Relational Learning" : [["Networks", "Relational Learning"]],
    "Non-convex Optimization" : [["Optimization"], ["Non-Convex Optimization"]],
    "Online Learning" : [["Online Learning"]],
    "Optimization" : [["Optimization"]],
    "Optimization and Graphical Models" : [["Optimization", [["Probabilistic Models"], ["Graphical Models"]]]],
    "Optimization: Convex and Non-convex" : [["Optimization", "Convex Optimization", "Non-Convex Optimization"]],
    "Privacy" : [["Privacy"]],
    "Privacy and Fairness" : [["Privacy", "Fairness"]],
    "Probabilistic Inference" : [["Probabilistic Inference"]],
    "Ranking and Preference Learning" : [["Ranking Learning", "Preference Learning"]],
    "Reinforcement Learning" : [["Reinforcement Learning"]],
    "Reinforcement Learning Theory" : [["Reinforcement Learning"]],
    "Reinforcement Learning and Bandits" : [["Reinforcement Learning", "Bandits"]],
    "Representation Learning" : [["Representation Learning"]],
    "Robust Statistics and Interpretability" : [["Robustness", "Interpretability"]],
    "Robust Statistics and Machine Learning" : [["Robustness"]],
    "Statistical Learning Theory" : [["Statistical Learning Theory"]],
    "Supervised Learning" : [["Supervised Learning"]],
    "Supervised and Transfer Learning" : [["Supervised Learning", "Transfer Learning"]],
    "Time Series" : [["Time-Series"]],
    "Transfer and Multitask Learning" : [["Transfer Learning", "Multi-Task Learning"]],
    "Unsupervised Learning" : [["Unsupervised Learning"]]
}